import Link from "next/link";
import { createF2TestSnapshot } from "@/app/f2-test/f2-test-snapshot";

interface F2TestPageProps {
  searchParams: Promise<{ seed?: string | string[] | undefined }>;
}

function firstSearchParam(value: string | string[] | undefined): string | undefined {
  return Array.isArray(value) ? value[0] : value;
}

function passLabel(pass: boolean): string {
  return pass ? "통과" : "실패";
}

export default async function F2TestPage({ searchParams }: F2TestPageProps) {
  const params = await searchParams;
  const seed = firstSearchParam(params.seed)?.trim() || "f2-fixture";
  const snapshot = createF2TestSnapshot(seed);
  return (
    <main className="mx-auto flex min-h-screen w-full max-w-7xl flex-col gap-8 px-5 py-10 sm:px-8">
      <header className="flex flex-col gap-4 border-b border-edge pb-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs uppercase tracking-[0.28em] text-muted">F2 / Content Contract</p><h1 className="mt-2 text-3xl font-semibold text-parchment">콘텐츠·불변식 검증</h1></div><nav className="flex flex-wrap gap-2 text-sm"><Link href="/f1-test" className="rounded border border-edge px-3 py-2 text-muted hover:bg-edge hover:text-parchment">F1 테스트</Link><Link href="/e1-test" className="rounded border border-edge px-3 py-2 text-muted hover:bg-edge hover:text-parchment">E1 지도 테스트</Link><Link href="/play" className="rounded border border-edge px-3 py-2 text-muted hover:bg-edge hover:text-parchment">프로토타입</Link></nav></div><p className="max-w-4xl text-sm leading-6 text-muted">F1 fixture와 F2 콘텐츠 데이터 계약을 같은 seed로 확인하는 서버 검증 화면이다. 효과 태그는 선언만 표시하며 실제 HP·신뢰·피해 계산은 하지 않는다.</p></header>
      <section className="rounded-lg border border-edge bg-panel p-5" data-testid="f2-f1-campaign"><div className="flex flex-wrap items-baseline justify-between gap-3"><h2 className="text-xl text-parchment">F1 캠페인 fixture</h2><span className="text-xs text-trust-up">계약 로드 성공</span></div><dl className="mt-4 grid gap-3 text-sm sm:grid-cols-2 lg:grid-cols-4"><div><dt className="text-xs text-muted">seed</dt><dd data-testid="f2-f1-seed" className="mt-1 font-mono text-parchment">{snapshot.f1.campaign.seed}</dd></div><div><dt className="text-xs text-muted">phase / rank</dt><dd className="mt-1 text-parchment">{snapshot.f1.campaign.phase} / {snapshot.f1.campaign.rank}</dd></div><div><dt className="text-xs text-muted">던전</dt><dd className="mt-1 text-parchment">{snapshot.f1.campaign.dungeonCount}개</dd></div><div><dt className="text-xs text-muted">파티</dt><dd className="mt-1 text-parchment">{snapshot.f1.campaign.partyCount}팀</dd></div></dl></section>
      <section className="rounded-lg border border-edge bg-panel p-5" data-testid="f2-f1-expedition"><h2 className="text-xl text-parchment">F1 탐험 fixture</h2><div className="mt-4 grid gap-3 text-sm text-muted sm:grid-cols-2 lg:grid-cols-4"><p>던전 <span className="font-mono text-parchment">{snapshot.f1.expedition.dungeonId}</span></p><p>파티 <span className="font-mono text-parchment">{snapshot.f1.expedition.partyId}</span></p><p>지도 지점 <span className="text-parchment">{snapshot.f1.expedition.mapNodeCount}개</span></p><p>경로 <span className="text-parchment">{snapshot.f1.expedition.pathCount}개</span></p></div></section>
      <section className="rounded-lg border border-edge bg-panel p-5" data-testid="f2-content-status"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-xl text-parchment">F2 전체 검증</h2><span className={snapshot.contentStatus === "pass" ? "rounded-full border border-trust-up/50 px-3 py-1 text-xs text-trust-up" : "rounded-full border border-trust-down/50 px-3 py-1 text-xs text-trust-down"}>{snapshot.contentStatus === "pass" ? "검증 성공" : "검증 실패"}</span></div>{snapshot.contentError ? <p className="mt-3 text-sm text-trust-down">{snapshot.contentError}</p> : <p className="mt-3 text-sm text-muted">사건·카드·아이템·보스 풀이 모든 F2 불변식을 통과했다.</p>}</section>
      <section className="rounded-lg border border-edge bg-panel p-5" data-testid="f2-events"><h2 className="text-xl text-parchment">사건 풀 <span className="text-sm text-muted">({snapshot.events.total}개 일반)</span></h2><div className="mt-4 grid gap-2 text-sm text-muted sm:grid-cols-4">{Object.entries(snapshot.events.byKind).map(([kind, count]) => <p key={kind}>{kind}: <span className="text-parchment">{count}개</span></p>)}</div><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><caption className="sr-only">사건 분류와 선택지 수</caption><thead className="border-b border-edge text-xs text-muted"><tr><th className="px-2 py-2 font-normal">ID</th><th className="px-2 py-2 font-normal">분류</th><th className="px-2 py-2 font-normal">사건</th><th className="px-2 py-2 font-normal">선택지</th></tr></thead><tbody>{snapshot.events.entries.map((event) => <tr key={event.id} className="border-b border-edge/70"><td className="px-2 py-2 font-mono text-parchment">{event.id}</td><td className="px-2 py-2 text-muted">{event.kind}</td><td className="px-2 py-2 text-parchment">{event.title}</td><td className="px-2 py-2 text-muted">{event.choiceCount}개</td></tr>)}</tbody></table></div></section>
      <section className="rounded-lg border border-edge bg-panel p-5" data-testid="f2-cards"><h2 className="text-xl text-parchment">정보 카드</h2><div className="mt-4 grid gap-2 text-sm text-muted sm:grid-cols-4">{Object.entries(snapshot.cards.byTruthType).map(([kind, count]) => <p key={kind}>{kind}: <span className="text-parchment">{count}개</span></p>)}<p>보스 주제: <span className="text-parchment">{snapshot.cards.bossSubjectCount}개</span></p></div><div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{snapshot.cards.entries.map((card) => <article key={card.id} className="rounded border border-edge p-3 text-sm"><p className="font-mono text-xs text-muted">{card.id}</p><p className="mt-1 text-parchment">{card.topic}</p><p className="mt-1 text-xs text-muted">{card.truthType} / {card.subject}</p></article>)}</div></section>
      <section className="rounded-lg border border-edge bg-panel p-5" data-testid="f2-items"><h2 className="text-xl text-parchment">아이템 ({snapshot.items.total}종)</h2><p className="mt-2 text-sm text-muted">유인용 미끼 포함 · 가짜 지도 노출: {snapshot.items.hasFakeMap ? "있음" : "없음"}</p><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{snapshot.items.entries.map((item) => <article key={item.id} className="rounded border border-edge p-3 text-sm"><p className="font-mono text-xs text-muted">{item.id}</p><p className="mt-1 text-parchment">{item.name}</p><p className="mt-1 text-muted">{item.kind} · {item.price} gold · {item.effectTags.join(", ")}</p></article>)}</div></section>
      <section className="rounded-lg border border-edge bg-panel p-5" data-testid="f2-bosses"><h2 className="text-xl text-parchment">등급별 보스</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{snapshot.bosses.entries.map((boss) => <article key={boss.id} className="rounded border border-edge p-3 text-sm"><p className="font-mono text-xs text-muted">{boss.id} / {boss.grade}</p><p className="mt-1 text-parchment">{boss.name}</p><p className="mt-1 text-muted">기본 피해 {boss.baseDamage}</p></article>)}</div></section>
      <section className="rounded-lg border border-edge bg-panel p-5" data-testid="f2-capacity"><h2 className="text-xl text-parchment">등급별 일반 사건 용량</h2><div className="mt-4 grid gap-2 sm:grid-cols-4">{snapshot.capacity.map((entry) => <div key={entry.grade} className="rounded border border-edge p-3 text-sm"><p className="text-parchment">{entry.grade}급</p><p className="mt-1 text-muted">필요 {entry.required} / 보유 {entry.available}</p><p className={entry.pass ? "mt-1 text-trust-up" : "mt-1 text-trust-down"}>{passLabel(entry.pass)}</p></div>)}</div></section>
      <section className="rounded-lg border border-edge bg-panel p-5" data-testid="f2-negative-cases"><h2 className="text-xl text-parchment">의도적 실패 fixture</h2><ul className="mt-4 grid gap-2 sm:grid-cols-2">{snapshot.negativeCases.map((entry) => <li key={entry.label} className="rounded border border-edge p-3 text-sm"><div className="flex justify-between gap-3"><span className="text-parchment">{entry.label}</span><span className={entry.pass ? "text-trust-up" : "text-trust-down"}>{passLabel(entry.pass)}</span></div><p className="mt-1 font-mono text-xs text-muted">{entry.errorCode ?? "오류 없음"}</p></li>)}</ul></section>
      <section className="rounded-lg border border-edge bg-panel p-5" data-testid="f2-reproducibility"><h2 className="text-xl text-parchment">seed 재현성</h2><p className="mt-3 text-sm text-muted">{snapshot.seed} fixture 동일 결과: <span className="text-trust-up">{snapshot.reproducibility.sameSeed ? "통과" : "실패"}</span></p><form method="get" className="mt-4 flex max-w-xl flex-col gap-3 sm:flex-row"><label htmlFor="seed" className="sr-only">테스트 seed</label><input id="seed" name="seed" defaultValue={snapshot.seed} className="min-w-0 flex-1 rounded border border-edge bg-ink px-3 py-2 text-sm text-parchment outline-none focus:border-trust-up" /><button type="submit" className="rounded border border-trust-up px-4 py-2 text-sm text-trust-up hover:bg-trust-up/10">seed 적용</button></form></section>
    </main>
  );
}
